version: '3'

services:

  cli:
    image: 'client-service:latest'
    container_name: cli
    depends_on:
      - app
    ports:
      - 5050:5050
    stdin_open: true 
    tty: true
    networks:
      - redis-cluster-compose

  app:
    image: 'storage-service:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
      - cluster_initiator
    networks:
      - redis-cluster-compose

  redis_1:
    image: 'redis:latest'
    container_name: redis_1
    ports:
      - 7006:7006
    hostname: redis_1
    volumes:
      - ./config/redis-1.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - redis-cluster-compose

  redis_2:
    image: 'redis:latest'
    container_name: redis_2
    hostname: redis_2
    ports:
      - 7001:7001
    volumes:
      - ./config/redis-2.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - redis-cluster-compose

  redis_3:
    image: 'redis:latest'
    container_name: redis_3
    hostname: redis_3
    ports:
      - 7002:7002
    volumes:
      - ./config/redis-3.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - redis-cluster-compose
  
  redis_4:
    image: 'redis:latest'
    container_name: redis_4
    hostname: redis_4
    ports:
      - 7003:7003
    volumes:
      - ./config/redis-4.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    depends_on:
      - redis_1
    networks:
      - redis-cluster-compose

  redis_5:
    image: 'redis:latest'
    container_name: redis_5
    networks:
      - redis-cluster-compose
    hostname: redis_5
    ports:
      - 7004:7004
    volumes:
      - ./config/redis-5.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    depends_on:
      - redis_2
  
  redis_6:
    image: 'redis:latest'
    container_name: redis_6
    networks:
      - redis-cluster-compose
    hostname: redis_6
    ports:
      - "7005:7005"
    volumes:
      - ./config/redis-6.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    depends_on:
      - redis_3

  cluster_initiator:
    container_name: cluster_initiator
    build:
      context: config
      dockerfile: Dockerfile
    tty: true
    ports:
      - 6699:6699
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
    networks:
      - redis-cluster-compose

networks:
  redis-cluster-compose:
    driver: bridge
